language: python
python:
 - "2.7"

# command to run tests
install:
 - pip install coverage
 - pip install codecov
script:
 - python -m unittest TestTriangle
 - python -m coverage run TestTriangle
 
after_success:
 - codecov
